---
swagger: "2.0"
info:
  title: location2
  description: locations api new
  version: 1.0.0
consumes:
- application/json
produces:
- application/json
paths:
  /locations:
    get:
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/location'
          examples:
            application/json: |-
              [
                {
                  "id": 1,
                  "name": "Kamarhati",
                  "type": "Regional Branch",
                  "status": "1",
                  "location": {
                    "lat": "-28.32555",
                    "lng": "-5.91531"
                  }
                },
                {
                  "id": 2,
                  "name": "Otranto",
                  "type": "Local Office",
                  "status": "1",
                  "location": {
                    "lat": "-8.01254",
                    "lng": "101.47364"
                  }
                },
                {
                  "id": 3,
                  "name": "Millesimo",
                  "type": "Headquarter",
                  "status": "1",
                  "location": {
                    "lat": "78.88435",
                    "lng": "99.05294"
                  }
                }
              ]
definitions:
  location:
    title: Root Type for location
    description: The root of the location type's schema.
    type: object
    properties:
      id:
        format: int32
        type: integer
      name:
        type: string
      type:
        type: string
      status:
        format: int32
        type: integer
      location:
        type: object
        properties:
          lat:
            type: string
          lng:
            type: string
    example: |-
      {
        "id": 1,
        "name": "Kamarhati",
        "type": "Regional Branch",
        "status": "1",
        "location": {
          "lat": "-28.32555",
          "lng": "-5.91531"
        }
      }
